name: CI

on:
  pull_request:
    branches:
      - master
    paths:
      - '**.txt'
      - '**.puml'

jobs:
  render:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Render PlantUML
        uses: lokkju/github-action-plantuml@v0.0.1
        with:
          args: "synopsis.txt"

      - name: Commit rendered
        uses: stefanzweifel/git-auto-commit-action@v2.5.0
        with:
          commit_message: Added rendered mind map
          branch: ${{ github.head_ref }}
          file_pattern: \*.png
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
