name: CI

on:
  pull_request:
    branches:
      - master
    paths:
      - '**.puml'
      - '**.yml'

jobs:
  render:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 1

      - name: Render PlantUML
        uses: lokkju/github-action-plantuml@v0.0.1
        with:
          args: "synopsis.puml"
      
      - name: Optimize image
        uses: docker://calibreapp/github-image-actions
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
